### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by alanmilinovic** [curif/cumulus-tv-m3u8-loader#24]
Hi, I am using your test.m3u and get this error.

```
Traceback (most recent call last):
  File "./m3u8_loader.py", line 406, in <module>
    startAt += process(m3uContent, provider, cumulustv, startAt)
  File "./m3u8_loader.py", line 263, in process
    if genres.strip() == "":
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by alanmilinovic** [comment]
I just realized that "group-title" was missing on some channel. Can you fix that in next release, because some channels doesn't has this attribute.

**Comment by alanmilinovic** [comment]
Ok so I just fixed it. Line 263 in file m3u8 should be changed with this one:
`if genres is None or genres.strip() == "":`

Please make a review and change it if you have time.

Thank you.

**Comment by curif** [comment]
Done.

**Comment by alanmilinovic** [comment]
Tnx!
